config = {}

config.bufferline = require('plugins.config.bufferline')
config.cmp = require('plugins.config.cmp')
config.copilot = require('plugins.config.copilot')
config.comment = require('plugins.config.comment')
config.dap = require('plugins.config.dap')
config.flash = require('plugins.config.flash')
config.indent = require('plugins.config.indent')
config.lspsaga = require('plugins.config.lspsaga')
config.lualine = require('plugins.config.lualine')
config.mason = require('plugins.config.mason')
config.nullls = require('plugins.config.nullls')
config.tabout = require('plugins.config.tabout')
config.telescope = require('plugins.config.telescope')
config.theme = require('plugins.config.theme')
config.filetree = require('plugins.config.filetree')
config.treesitter = require('plugins.config.treesitter')
config.dashboard = require('plugins.config.dashboard')
config.outline = require('plugins.config.outline')
config.fold = require('plugins.config.fold')
config.session = require('plugins.config.session')
config.surround = require('plugins.config.surround')
config.osc52 = require('plugins.config.osc52')

return config
