config = {}

config.cmp = require('plugins.config.cmp')
config.copilot = require('plugins.config.copilot')
config.comment = require('plugins.config.comment')
config.dap = require('plugins.config.dap')
config.flash = require('plugins.config.flash')
config.indentline = require('plugins.config.indentline')
config.hlchunk = require('plugins.config.hlchunk')
config.lspsaga = require('plugins.config.lspsaga')
config.lsp = require('plugins.config.lsp')
config.tabout = require('plugins.config.tabout')
config.telescope = require('plugins.config.telescope')
config.ui = require('plugins.config.ui')
config.filetree = require('plugins.config.filetree')
config.treesitter = require('plugins.config.treesitter')
config.dashboard = require('plugins.config.dashboard')
config.outline = require('plugins.config.outline')
config.fold = require('plugins.config.fold')
config.surround = require('plugins.config.surround')
config.osc52 = require('plugins.config.osc52')
config.latex = require('plugins.config.latex')
config.noice = require('plugins.config.noice')

return config
