add_newline = false

format = """
[╭─](white) $os$hostname$directory$python$git_branch$git_status$kubernetes
[╰─](white)$character"""

[character]
success_symbol = '[❯](cyan)[❯](blue)'
error_symbol = '[❯](red)[❯](blue)'

[directory]
style = "cyan"
format = '[ ]($style)[$path]($style)[$read_only]($read_only_style) '

[os]
disabled = false

[os.symbols]
Arch = " "
Debian = " "
Macos = " "
Manjaro = " "
NixOS = " "
Ubuntu = " "

[hostname]
style = 'white'
ssh_only = false
format = '[$ssh_symbol$hostname]($style) '
ssh_symbol = ' '

[kubernetes]
disabled = true
symbol = '󱃾 '
style = 'purple'
format = '[$symbol$context(\($namespace\))]($style) '

[python]
symbol = ' '
style = 'blue bold'
version_format = '${raw}'
format = '[${symbol}${pyenv_prefix}(${version})]($style) '
detect_extensions = []

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
