alias c="clear"
alias s="ssh"
alias l="lsd"
alias ls="lsd"
alias ll="lsd --tree --depth 2"
alias checklog="journalctl -xefu"
alias vi="nvim"

alias cat="bat --style=plain --paging=never"
alias top="htop"
alias cp="rsync -az"
