[
  (atx_heading
    (atx_h1_marker))
] @text.title1

[
  (atx_heading
    (atx_h2_marker))
] @text.title2

[
  (atx_heading
    (atx_h3_marker))
] @text.title3

[
  (atx_heading
    (atx_h4_marker))
] @text.title4

[
  (atx_heading
    (atx_h5_marker))
] @text.title5

[
  (atx_heading
    (atx_h6_marker))
] @text.title6

[
  (thematic_break)
  (list
    (list_item
      (list_marker_minus)
      (paragraph
        (inline))))
  (list
    (list_item
      (list_marker_plus)
      (paragraph
        (inline))))
  (list
    (list_item
      (list_marker_star)
      (paragraph
        (inline))))
  (list
    (list_item
      (list_marker_dot)
      (paragraph
        (inline))))
  (list
    (list_item
      (list_marker_parenthesis)
      (paragraph
        (inline))))
] @punctuation.special2

(block_quote) @text.quote

(list_item
  (task_list_marker_checked)
  (paragraph
    (inline))) @text.todo.checked

(list_item
  (task_list_marker_unchecked)
  (paragraph
    (inline))) @text.todo.unchecked

;; end of my customization

(info_string) @label

(pipe_table_header
  (pipe_table_cell) @markup.heading)

(pipe_table_header
  "|" @punctuation.special)

(pipe_table_row
  "|" @punctuation.special)

(pipe_table_delimiter_row
  "|" @punctuation.special)

(pipe_table_delimiter_cell) @punctuation.special

; Code blocks (conceal backticks and language annotation)
(indented_code_block) @markup.raw.block

((fenced_code_block) @markup.raw.block
  (#set! "priority" 90))

(fenced_code_block
  (fenced_code_block_delimiter) @markup.raw.delimiter
  (#set! conceal ""))

(fenced_code_block
  (info_string
    (language) @conceal
    (#set! conceal "")))

(link_destination) @markup.link.url

[
  (link_title)
  (link_label)
] @markup.link.label


; NOTE: The following has been commented out due to issues with spaces in the
; list marker nodes generated by the parser. If those spaces ever get captured
; by a different node (e.g. block_continuation) we can safely re-add these
; conceals.
; ;; Conceal bullet points
; ([(list_marker_plus) (list_marker_star)]
;   @punctuation.special
;   (#offset! @punctuation.special 0 0 0 -1)
;   (#set! conceal "•"))
; ([(list_marker_plus) (list_marker_star)]
;   @punctuation.special
;   (#any-of? @punctuation.special "+" "*")
;   (#set! conceal "•"))
; ((list_marker_minus)
;   @punctuation.special
;   (#offset! @punctuation.special 0 0 0 -1)
;   (#set! conceal "—"))
; ((list_marker_minus)
;   @punctuation.special
;   (#eq? @punctuation.special "-")
;   (#set! conceal "—"))


[
  (block_continuation)
  (block_quote_marker)
] @punctuation.special

(backslash_escape) @string.escape

(inline) @spell
