name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ch4xer/dev:${{ github.sha }}
        docker tag ch4xer/dev:${{ github.sha }} ch4xer/dev:latest

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKER_HUB_USERNAME}}
        password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}

    - name: Push Docker image to Docker Hub
      run: |
        docker push ch4xer/dev:latest
        docker push ch4xer/dev:${{ github.sha }}
        
